[package]
name = "main"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"
tonic = { version = "0.14.2", features = ["transport"] }
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"