[package]
name = "loadgen_simple"
version = "0.1.0"
edition = "2024"

[dependencies]
main = { version = "0.1.0", path = "../../main" }
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
tonic.workspace = true
async-stream.workspace = true
